[workspace]
authors = ["Vikram Rangarajan <rangarav@purdue.edu>"]
channels = ["conda-forge"]
name = "geta"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.geta]
channels = ["pytorch", "nvidia", "conda-forge", "main", "r", "msys2"]

[feature.geta.dependencies]
python = "3.9.*"
pytorch = "==2.2.0"
torchvision = ">=0.15.0,<0.20.0"
numpy = "<2.0.0"
matplotlib = ">=3.5.0"
scikit-image = ">=0.19.0"
pip = "*"
tqdm = ">=4.67.1,<5"
typer = ">=0.16.1,<0.17"
transformers = ">=4.33.3,<5"
datasets = ">=2.19.2,<3"
h5py = ">=3.9.0,<4"
einops = ">=0.8.1,<0.9"
timm = ">=1.0.19,<2"

[feature.geta.pypi-dependencies]
pipreqs = ">=0.5.0"

[environments]
geta = { features = ["geta"], no-default-feature = true }
